README.md
Reorders the suggestions for getting added to the list to add emphasis to CC apps over unapproved repos, makes it less certain that a repo will be added to the unapproved list.
=> Reorder suggestions, make draper happy <3

repositories.yaml
This adds my alternative repo for Pokecord to the approved listing.
=> add pokecord to approved listing

repositories.yaml
Add https://github.com/Vexed01/Vex-Cogs to the list of unapproved repos
=> Add vex-cogs to unapproved list

.github/workflows/run-indexer.yml
I missed that in the previous PR and this should be unneeded as we do the same on Red's main repo:
https://github.com/Cog-Creators/Red-DiscordBot/blob/01561fbe07dc3783d87142b030370eeb2561c26e/.github/workflows/prepare_release.yml#L19
=> Use shallow clone for clone of Red-Index as well

repositories.yaml
Please add https://github.com/siu3334/owo-cogs to the list of unapproved repos. Thank you.
=> Add owo-cogs to unapproved list

repositories.yaml
As said in #cog-creators in the Red - Cog Support channel, I want to be done forever with my cogs and I accept to lose my [Cog Creator's privileges respecting the policy 10](https://github.com/Cog-Creators/Red-Policies/blob/master/policies/active/0010.md#breakdown).
You're gently asked to not add it into the unapproved list. Thank you.
=> Remove Predeactor-Cogs from approved repos

repositories.yaml
This PR adds lui-cogs-v3 to the unapproved list.
I think I'm still missing some keys in the per-cog info.json files, will continue to sort those out.
=> Add lui-cogs-v3 to unapproved list

repositories.yaml
Cleaning up and improving the cogs is still on my miles long todo list so unapproved for now.
=> Add goonstation/gooncogs to the unapproved list

repositories.yaml
Pokecord is no longer maintained, thus moving to unapproved.
LastFM is a huge cog that sits on it's own repo, similar to pokecord however is maintained.
=> flaree: make pokecord-red unapproved, add lastfm-red to approved

repositories.yaml
I didn't do this earlier, because the cogs in this repo are there because they are fairly niche compared to my main repo, but enough people have wanted some of this kind of functionality that I might as well let them appear on the index :P
=> Add FlameBountyCogs to the unapproved section

repositories.yaml
The repo has not existed for 2 months, see: https://github.com/Cog-Creators/Red-Index/commit/36b2a0023e6036127bcf524b3ee4a8dcbdc19717
=> Remove tpun from unapproved list as it no longer exists

repositories.yaml
Just leaving my 2 cents here, at the moment it only contains my Brainfuck-Cog, but will definitely add more in the near future
=> Add T14D3-Cogs to unapproved repositories

repositories.yaml
Please note the `cryptochannel` cog is still a work in progress, the clock cog is fully operational and works with red bot 3.5
=> add cryptolover-cogs

repositories.yaml
The repo has been cogless since March, so removing it would make sense. I can see a case for keeping it since it doesn't technically break any rules, but it does annoy the indexer so :P.
=> Remove nukdokplex-cogs

repositories.yaml
CoastalCommits is a [Forgejo](https://forgejo.org/) instance. I haven't modified it in any way from the official docker images, the only modifications I've made are to css templates and configuration files. If this is an issue, I could set up a push mirror on GitHub, but I'd prefer not to if I can avoid it.
=> Add SeaCogs to the unapproved repository list

repositories.yaml
https://github.com/space-wizards/wizard-cogs
We are *probably* gonna be getting approved as well at some point. But for now, I feel like this is good too.
Right now only 2 of our cogs are gonna go out in the wild on the index and are the most useful ones. "Autoresponder" is an internal meme and another a pretty normal echo command. They are both marked as hidden in their json.
From what I understood when I asked on the redbot discord server, since I'm an org member (of wizard cog's organization) I'm allowed to add us here.
=> Add wizard cogs to unapproved list

repositories.yaml
[FalcomBog-Cogs](https://github.com/nmbook/FalcomBot-cogs/commit/a32c8a2a55a2bb6d204749371ef450df591f8e2f) and [Cogs.v3](https://github.com/dualmoon/Cogs.v3/commit/90d2a56c820a51d270344eac9db523089f42cf47) have received updates which make them load on 3.5. They have been removed from the list of flagged cogs.
=> Remove flag from updated repos

repositories.yaml
add my cog repo to the unapproved section of the index 
(feedback is always welcome just to add)
=> add ben-cogs to unapproved 

repositories.yaml
recently changed my username on coastalcommits, just ensuring that the repo name isn't stolen without me noticing
=> change my repository (SeaswimmerTheFsh/SeaCogs) to the updated url (Sea/Cogs)

repositories.yaml
currently only has PICO-8 and Invasion cogs
=> added Chovin/Dumb-Cogs to unapproved

repositories.yaml
Added the github link to spideysimp-cogs to the unapproved list
=> Add spideysimp-cogs to unapproved

repositories.yaml
Request to add my repository to the unapproved section
=> Add vti-cogs to unapproved section

repositories.yaml
Discussed with the Cog Creator. Name change so that the repo name shown in the URL is more of a descriptor of the Cog Creator than "RedBot-Cogs".
=> Rename RedBot-Cogs to Reediculous-Cogs

repositories.yaml
We've changed our org title and are updating the location of our cogs here.
=> Updating repo destination

repositories.yaml
Repo and associated account are a 404.
=> Remove ShitShowCogs from unapproved

repositories.yaml
The repo is archived and the `TagScript` version the cog is locked to appears to not support dpy 2.0. The cog does not appear to function at all in this state, and having it listed only adds confusion with a working albeit unapproved version fork showing up at the same time.
=> Delist slashtags from phen-cogs
