Cog-Creators/Red-Index

repositories.yaml

Adding my repo to the unapproved cog list..

Added npc-cogs in unapproved

---

repositories.yaml

Added kreusadacogs repo as unapproved

kreusadacogs

---

repositories.yaml

https://cogboard.red/t/approved-yamicogs/793

Add Yami to the approved list

---

repositories.yaml

https://cogboard.red/t/approved-wyn-cogs/801

Add Wyn to approved

---

repositories.yaml

My github username changed, therefore this is will need to be updated

Update kreusada's repo

---

repositories.yaml

Apologies, my username changed after I submitted the application therefore I forgot to update it in the cogboard.

Edit kreusada's username

---

.github/workflows/run-indexer.yml
git-retry.sh
parser.py

Add auto-retry to git cloning

---

repositories.yaml

Adds Jojo's cogs (my cogs?) to unapproved cogs

Add JojoCogs to unapproved list

---

.github/workflows/run-indexer.yml

See: https://docs.github.com/en/actions/reference/authentication-in-a-workflow#permissions-for-the-github_token
And: https://docs.github.com/en/rest/reference/permissions-required-for-github-apps

Update workflows with needed permissions

---

repositories.yaml

Added my cogs to the unapproved list while I go through the minutia of cleaning up / standardizing docs for the approval process.

Add Eris-Cogs to unapproved list

---

repositories.yaml

Add GamEraBot-cogs to unapproved section

Add GamEraBot-cogs to unapproved section

---

repositories.yaml

[PlusyCogs](https://github.com/NoPlagiarism/PlusyCogs)

Add PlusyCogs to unapproved list

---

repositories.yaml

[matcha-cogs](https://github.com/matchatealeaf/matcha-cogs)

Add matcha-cogs to unapproved list

---

repositories.yaml

I am no longer maintaining these cogs so I would like to remove it from the cog index

Remove Finger-cogs

---

repositories.yaml

Add YeahCogs to unapproved repository list

---

.github/workflows/run-indexer.yml

GitHub is yelling at us for Node 16, So lets update the deps that we can.

Update the action dependencies

---

repositories.yaml

Includes 1 cog, ChatGPT. It's my first cog and I'd be happy to receive feedback on it. Thanks!

Add CalaMari-Cogs repo to unapproved cogs

---

repositories.yaml

Includes cogs for chatgpt and https://dnd5eapi.co/

Add skylark95-cogs to unapproved

---

repositories.yaml

Add bz-cogs repo to unapproved cogs 

---

repositories.yaml

Just adding my 3 active cogs, let me know if there's something I need to change in case of
:D

Add glas-cogs repo to unapproved cogs

---

indexer.py
parser.py

Makes it easier to go through repos locally and doesn't really hurt anything (unless I made an oopsie :upside_down_face:).

Include friendly repo name in cache dir name

---

repositories.yaml

just a 1 character change, thanks!

Rename bz_cogs repo

---

repositories.yaml

Update repositories.yaml to Re-add Fox-V3

Re-add Fox-V3 after update

---

repositories.yaml

This is my first time working with python and making cogs, please let me know if there is something i need to do.  I just added two cogs that seems fun to have.

Add fakecogs to unapproved repositories

---

repositories.yaml

Remove bz from unapproved

---

repositories.yaml

added Viking studios to unnaproved

Added Viking Studios VSCogs to unnaproved list

---

repositories.yaml

Add BackRoomCogs to the unofficial repo list

Add BackRoomCogs to the unofficial repo list

---

repositories.yaml

Add Bartixxx-Cogs to unapproved

Add Bartixxx-Cogs to unapproved

---

repositories.yaml

I just completed my second cog and would like to be added to the unapproved list. I understand reviews aren't required, but I am open to any feedback, thank you!
Sorry about the multiple commits!

Add CCCogs to unapproved

---

repositories.yaml

Added my (Drago Prime) Prime-Cogs repository to unapproved repos.

Added Prime-Cogs

---

repositories.yaml

https://github.com/duduws/duduw-cogs/

Added duduws-cogs to unapproved section

---

repositories.yaml

Added my cog for publishing on the site

Add ntfy-cog to unapproved

---

repositories.yaml

Reopening pull request due to increasing user requests / messages

Add botagas-Cogs to the repositories list
